### PR TITLE
Move package metadata from setup.py into package

### PR DESCRIPTION
**Pull request by jayvdb**
Also add CHANGELOG.md

### CODE REVIEW

**Comment by jayvdb** [comment]
gah; do not merge.
setup.py changes were copied from https://github.com/jayvdb/changes/blob/master/setup.py , which is MIT.

**Comment by jayvdb** [comment]
A PD version now exists. ;-)

**Comment by jayvdb** [comment]
:-1:
will rebase and update after the remaining pull requests are merged, so we can label it as the next release.

**Comment by jayvdb** [comment]
@legoktm , if you're not liking this approach, I'll resubmit the changelog, and we can get on with releasing 0.8.0 without the package metadata changes.

**Comment by legoktm** [comment]
Looks good! The only question I have is when releasing a new version, how does that commit sha1 end up in the changelog?

There'll be a "Release 0.8.0" commit, then I do another commit to add the sha1 to the changelog, do I end up tagging the second commit?

**Comment by jayvdb** [comment]
That is a problem of having sha1's as the main identifiers, and there isnt a neat way around it without an extra commit which isnt in the changelog.  IMO yes, the extra commit would be tagged.

We could swap over to using PR # / Issue # where they exist, and avoid direct commits in the future.

**Comment by hugovk** [comment]
What's the status of this? 

Looking forward to a release soon :)

**Comment by legoktm** [comment]
Sorry about the delay @hugovk and @jayvdb , I've now released and uploaded 0.8.0 to pypi. Thanks for all of your contributions so far!

**Comment by hugovk** [comment]
:+1:

**Pull request merged**
